### ISSUE TITLE
https://ocjs.org/reference-docs  404

### ISSUE THREAD

**Issue by atlas1119** [donalffons/opencascade.js#113]
api doc do not working

**Comment by donalffons** [comment]
Thanks for reporting that (I haven't noticed that, yet). Will fix that as soon as possible!

**Comment by donalffons** [comment]
For the moment, you can use https://ocjs.org/reference-docs/index.html .

**Comment by donalffons** [comment]
This should now be fixed. Visiting https://ocjs.org/reference-docs will perform a server-side redirect to https://ocjs.org/reference-docs/ (with a trailing-slash), which is required for typedoc's default behavior of using relative path URLs. For consistency, I'm also using trailing slashes on the Docusaurus website, now.
Thanks again for the report!
