### ISSUE TITLE
how to display 2d, like HLR, support to 2D ? 

### ISSUE THREAD

**Issue by atlas1119** [donalffons/opencascade.js#119]

**Comment by donalffons** [comment]
Well, most of the time you would use a GPU to create a rasterized 2D-representation of 3D geometry. If a rasterized visualization of outlines is what you are looking for, check out how CascadeStudio's viewport draws outlines in its viewport. If you want to show hidden lines too, you could achieve that using additional render passes and potentially same fragment shader tricks.

If you want a vectorized representation (as opposed to a rasterized one), you should probably do more research into the `HLR` stuff that comes with OpenCascade, e.g. in this [document](https://dev.opencascade.org/doc/overview/html/occt_user_guides__modeling_algos.html#occt_modalg_10).
