### ISSUE TITLE
Add typescript definitions for extracting exception data

### ISSUE THREAD

**Issue by JohannesMerkt** [donalffons/opencascade.js#135]
As described in https://ocjs.org/docs/advanced/exceptions/catch-exceptions you can use 
```js
try {
  const disc = new oc.BRepPrimAPI_MakeCone_1(1, 0, 0);
} catch (e) {
  if(typeof e === "number") {
    const exceptionData = oc.OCJS.getStandard_FailureData(e);
    console.log(`That didn't work because: ${exceptionData.GetMessageString()}`);
  } else {
    console.log("Unkown error");
  }
}
```
to retrive the actual exception data the error number points to. However the typescript definition does not know about OCJS and its sub functions. So workarounds are needed
```ts
try {
  const disc = new oc.BRepPrimAPI_MakeCone_1(1, 0, 0);
} catch (e) {
  if(typeof e === "number") {
    const exceptionData: Standard_Failure = (oc as any).OCJS.getStandard_FailureData(e);
    console.log(`That didn't work because: ${exceptionData.GetMessageString()}`);
  } else {
    console.log("Unkown error");
  }
}
```

**Comment by JohannesMerkt** [comment]
If it is as simple as adding those to the opencascade.full.d.ts file in typedoc-reference-docs. I could create a merge request

**Comment by donalffons** [comment]
This works now in `2.0.0-beta.ae74abe`.
![image](https://user-images.githubusercontent.com/33040347/170248043-f1862071-7413-4a7c-bdf9-04297e7a3df7.png)
