### ISSUE TITLE
RuntimeError in nodejs

### ISSUE THREAD

**Issue by cczw2010** [donalffons/opencascade.js#147]
This error keeps me from continuing。

### Env

- opencascade.js  2.0.0-beta.5d338b8
- nodejs v16.0.0  &  v14.13.1
- mac 10.15.7

### code
```
import initOpenCascade from "opencascade.js/dist/node.js";
const opencascade = await initOpenCascade()
```

### console
```
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #1113 failed: Invalid opcode (enable with --experimental-wasm-threads) @+1022999). Build with -sASSERTIONS for more info.
    at abort (file:///.../node_modules/opencascade.js/dist/opencascade.full.js:9:10533)
    at file:///.../node_modules/opencascade.js/dist/opencascade.full.js:9:12477
```

**Comment by donalffons** [comment]
I cannot reproduce that error message by downloading the Node [starter template](https://ocjs.org/starter-templates) and using the Node.js and OpenCascade.js versions you mentioned.

However, I noticed that there seems to be a massive regression in startup times and memory usage, starting with version `2.0.0-beta.af1af03` and NodeJS versions <= `v17`. The difference between those version is just [this single commit](https://github.com/donalffons/opencascade.js/commit/af1af03d756738ee83d395584dd7263a1669774b). I need to investigate that further.

In the mean time, I would recommend using NodeJS `v18` or later. If you can't use that version (e.g. that's not available on GCP or AWS functions), try to stick with OpenCascade.js `2.0.0-beta.ae74abe` for the moment. I will post updates here regarding the regression.

**Comment by cczw2010** [comment]
Thanks for the replay ,i'll try .

**Comment by donalffons** [comment]
I have since reverted that problematic commit - so I believe your error should be gone in the latest version `2.0.0-beta.94e2944`. However, at some point I want to research this better - it would be great to have freetype support in OCJS.

**Comment by cczw2010** [comment]
great!
