### ISSUE TITLE
Open *.igs file got `getpwuid: TODO` error

### ISSUE THREAD

**Issue by J-F-Liu** [donalffons/opencascade.js#78]
using 2.0 beta
![image](https://user-images.githubusercontent.com/1472963/127346080-719a8d1c-6559-4c64-88d6-6b8244f1e664.png)

**Comment by donalffons** [comment]
Thanks for reporting. That function `getpwuid` is currently not implemented in Emscripten. I have made a patch for this issue a while back [in this commit](https://github.com/donalffons/opencascade.js/commit/9416ee8f67e1b5249748f202a92f39d5c8117995), but for some reason it doesn't seem as if this is getting applied correctly.

I will look into that issue.

**Comment by donalffons** [comment]
I added the patch back in - loading IGES files works now.
I will also add a test (tracking that [here](https://github.com/donalffons/opencascade.js/issues/74)) to make sure that "features" like this don't get removed accidentally, again.
